### ISSUE TITLE
Id has no attribute 

### ISSUE THREAD

**Issue by Peyton-F** [svaxyyy/discord.py-Captcha#1]
ran the bot and when i complete the Captcha successfully it gives me this error:

`
D:\Default Download\discord.py-Captcha-main\discord.py-Captcha-main>C:/Users/peyto/AppData/Local/Programs/Python/Python39/python.exe "d:/Default Download/discord.py-Captcha-main/discord.py-Captcha-main/Captcha.py"
We have logged in as Fun bot test#7155
9334
Ignoring exception in command captcha:
Traceback (most recent call last):
  File "C:\Users\peyto\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped  
    ret = await coro(*args, **kwargs)
  File "d:\Default Download\discord.py-Captcha-main\discord.py-Captcha-main\Captcha.py", line 187, in captcha
    await member.add_roles(role)
  File "C:\Users\peyto\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\member.py", line 777, in add_roles
    await req(guild_id, user_id, role.id, reason=reason)
AttributeError: 'NoneType' object has no attribute 'id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\peyto\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke   
    await ctx.command.invoke(ctx)
  File "C:\Users\peyto\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke  
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\peyto\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped  
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'id'
`

**Comment by svaxyyy** [comment]
Tomorrow I’ll fix it the error is in add_roles I think I have to change it a bit so I can use add_role

**Comment by svaxyyy** [comment]
no error in the code if im runnung it maybe you entered a role wich is higher or smt

**Comment by Peyton-F** [comment]
> no error in the code if im runnung it maybe you entered a role wich is higher or smt

What python version are you using? Im still getting the same error yet my bot has all perms and has is higher than the role trying to be given

**Comment by svaxyyy** [comment]
Im using the newest which is 3.9.6 I think
